config/routes.rb
Rails.application.routes.draw do  
  resources :sos do
    resources :sub_service_orders do
      resources :materials
    end
  end
  resources :material_classes
  resources :military_organizations
  resources :section_military_organizations
  
  

  root 'sos#index'

  get 'sub_service_orders/:id/purchase' => 'catalog#purchase', as: :purchase

end

app/models/military_organization.rb
class MilitaryOrganization < ActiveRecord::Base
	validates_presence_of :name
	validates_presence_of :acronym

	validates_length_of :name, :minimum => 2
	validates_length_of :name, :maximum => 60
	validates_length_of :acronym, :minimum => 2
	validates_length_of :acronym, :maximum => 15

	#RELACIONAMENTOS
	has_many :sos
end

app/controllers/military_organizations_controller.rb
class MilitaryOrganizationsController < ApplicationController
	def index
		@military_organizations = MilitaryOrganization.all
	end

	def new
		@military_organization = MilitaryOrganization.new
	end

	def create
		@military_organization = MilitaryOrganization.new(military_organization_params)
		if @military_organization.save then
			redirect_to military_organizations_path
		else
			render :new
		end
	end

	def destroy
		begin
			@military_organization = MilitaryOrganization.find(params[:id])

			if @military_organization.sos == nil or @military_organization.sos.length == 0 then
				@military_organization.destroy
			end

			redirect_to military_organizations_path
			
		rescue ActiveRecord::RecordNotFound
			redirect_to military_organizations_path
		end	
	end

	def edit
		begin
			@military_organization = MilitaryOrganization.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			redirect_to military_organizations_path
		end
	end

	def update
  		begin
  			@military_organization = MilitaryOrganization.find(params[:id])
  			if @military_organization.update(military_organization_params) then 
  				redirect_to military_organizations_path
  			else
  				render :edit
  			end
  		rescue ActiveRecord::RecordNotFound
  			redirect_to military_organizations_path
  		end
	end

	def military_organization_params
      params.require(:military_organization).permit(:name, :acronym)
    end
end

app/helpers/military_organizations_helper.rb
module MilitaryOrganizationsHelper
end

app/views/military_organizations/edit.html.erb
<h2><b>Editing - military organization</b></h2>

<%= form_for(@military_organization) do |f| %>
  <table id="table_edit_military_organization">
    <tr id="name">
      <div class="field">
        <td id="name_label"><%= f.label :name %></td>
        <td id="name_textfield"><%= f.text_field :name %></td>
      </div>
    </tr>
    <tr id="acronym">
      <div class="field">
        <td id="acronym_label"><%= f.label :acronym %></td>
        <td id="acronym_textfield"><%= f.text_field :acronym %></td>
      </div>
    </tr>
  </table>
  <br>
  <div class="actions">
	 <%= f.submit %>
  </div>
 
<% end %>

<%= link_to 'Back', military_organizations_path %>

app/views/military_organizations/index.html.erb
<h2><b>MILITARY ORGANIZATIONS</b></h2> 
<br>
<table id="military_organizations">
	<tr id="headers">
		<th>NAME</th>
		<th>ACRONYM</th>
		<th colspan="2">OPTIONS</th>
	</tr>
	<% @military_organizations.each do |military_organization| %>
		
		<tr>
			<td id="military_organization_name_<%= military_organization.id %>"><%= military_organization.name %></td>
			<td id="military_organization_acronym_<%= military_organization.id %>"><%= military_organization.acronym %></td>
			<td id="military_organization_edit_<%= military_organization.id %>"><%= link_to 'Edit', edit_military_organization_path(military_organization) %></td>
			<td id="military_organization_destroy_<%= military_organization.id %>"><%= link_to 'Destroy', military_organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>

</table>
<br>
<%= link_to 'Create new military organization', new_military_organization_path %>
<br />
<%= link_to 'Back', sos_path %>

app/views/military_organizations/new.html.erb
<h2><b>Creating a new military organization </b></h2>

<%= form_for(@military_organization) do |f| %>
  <table id="table_new_military_organization">
    <tr id="name">
      <div class="field">
        <td id="name_label"><%= f.label :name %></td>
        <td id="name_textfield"><%= f.text_field :name %></td>
      </div>
    </tr>
    <tr id="acronym">
      <div class="field">
        <td id="acronym_label"><%= f.label :acronym %></td>
        <td id="acronym_textfield"><%= f.text_field :acronym %></td>
      </div>
    </tr>
  </table>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', military_organizations_path %>