config/routes.rb
Rails.application.routes.draw do  
  resources :sos do
    resources :sub_service_orders do
      resources :materials
    end
  end
  resources :material_classes
  resources :military_organizations
  resources :section_military_organizations
  
  

  root 'sos#index'

  get 'sub_service_orders/:id/purchase' => 'catalog#purchase', as: :purchase

end

app/models/so.rb
class So < ActiveRecord::Base
	  validates_presence_of :material_description
	 
	  validates_presence_of :sender_name
	  validates_presence_of :sender_phone
	  validates_presence_of :total_amount
    validates_presence_of :guide_number
	  validates_length_of :material_description, :minimum => 2
	  validates_length_of :material_description, :maximum => 100
    validates_length_of :sender_name, :minimum => 2
  	validates_length_of :sender_name, :maximum => 20
  	validates_length_of :sender_phone, :minimum => 13
  	validates_length_of :sender_phone, :maximum => 15
  	validates :guide_number,length: { maximum: 10 }       
    validates :guide_number,length: { minimum: 2 } 
  
  	validates_format_of :sender_phone, :with => /\((\d{2})\)+(\d{4})-(\d{4})/
  
  	#validacoes relacionamento
  	validates_presence_of :material_class_id
  	validates_presence_of :military_organization_id
  
  
  	#relacionamentos
  	belongs_to :material_class  
  	belongs_to :military_organization
  	has_many :sub_service_orders
end

app/controllers/sos_controller.rb
class SosController < ApplicationController
	def index
		@sos = So.all
	end

	def new
		@so = So.new
	end

	def create
		@so = So.new(so_params)
		if @so.save then
			redirect_to sos_path
		else
			render :new
		end
	end

	def show
		begin
			@so = So.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			redirect_to sos_path
		end
	end

	def destroy
		begin
			@so = So.find(params[:id])
			if @so.sub_service_orders == nil or @so.sub_service_orders.length == 0 then
				@so.destroy
			end	
			redirect_to sos_path
		rescue ActiveRecord::RecordNotFound
			redirect_to sos_path
		end		
	end

	def edit
		begin
			@so = So.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			redirect_to sos_path
		end
	end

	def update
		begin
  			@so = So.find(params[:id])
  			if @so.update(so_params) then 
  				redirect_to sos_path
  			else
  				render :edit
  			end
  		rescue ActiveRecord::RecordNotFound
  			redirect_to sos_path
  		end
	end

	private

    # Never trust parameters from the scary internet, only allow the white list through.
    def so_params
      params.require(:so).permit(:material_description, :guide_number, :sender_name, :sender_phone, :total_amount, :material_class_id, :military_organization_id)
    end

end

app/helpers/sos_helper.rb
module SosHelper
end

app/views/sos/edit.html.erb
<h2><b>Editing - Service Order</b></h2>

<%= form_for(@so) do |f| %>
   <table id="table_edit_so">
    <tr id="material_description">
      <div class="field">
        <td><%= f.label :material_description %></td>
        <td><%= f.text_field :material_description %></td>
      </div>
    </tr>
    <tr id="guide_number">
      <div class="field">
        <td><%= f.label :guide_number %></td>
        <td><%= f.text_field :guide_number %></td>
      </div>
    </tr>
    <tr id="sender_name">
      <div class="field">
        <td><%= f.label :sender_name %></td>
        <td><%= f.text_field :sender_name %></td>
      </div>
    </tr>
    <tr id="sender_phone">
      <div class="field">
        <td><%= f.label :sender_phone %></td>
        <td><%= f.text_field :sender_phone %></td>
      </div>
    </tr>
    <tr id="total_amount">
      <div class="field">
        <td><%= f.label :total_amount %></td>
        <td><%= f.text_field :total_amount %></td>
      </div>
    </tr>
    <tr id="material_class">
      <div class="field">
        <td><%= f.label :material_class_id %></td>
        <td><%= f.select :material_class_id, MaterialClass.all.collect{|p| [p.name, p.id]}, { include_blank: true } %></td>
      </div>
    </tr>
    <tr id="military_organization">
      <div class="field">
        <td><%= f.label :military_organization_id %></td>
        <td><%= f.select :military_organization_id, MilitaryOrganization.all.collect{|p| [p.name, p.id]}, { include_blank: true } %></td>
      </div>
    </tr>
  </table>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<br>

<%= link_to 'Back', sos_path %>

app/views/sos/index.html.erb
<h2><b>SERVICE ORDERS</b></h2> 
<br>
<table id="sos">
	<tr>
		<th>MATERIAL DESCRIPTION</th>
		<th>GUIDE NUMBER</th>
		<th colspan="3">OPTIONS</th>
	</tr>
	<% @sos.each do |so| %>
		<tr>
			<td id="so_material_description_<%= so.id %>"><%= so.material_description %></td>
			<td id="so_guide_number_<%= so.id %>"><%= so.guide_number %></td>
			<td id="so_show_<%= so.id %>"><%= link_to 'Show', so %></td>
			<td id="so_edit_<%= so.id %>"><%= link_to 'Edit', edit_so_path(so) %></td>
			<td id="so_destroy_<%= so.id %>"><%= link_to 'Destroy', so, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>
<br />
<%= link_to 'Create new service order', new_so_path %>

<br />
<%= link_to 'Manage material classes', material_classes_path %>

<br />
<%= link_to 'Manage military organizations', military_organizations_path %>

<br />
<%= link_to 'Manage section military organizations', section_military_organizations_path %>

app/views/sos/new.html.erb
<h2><b>Creating a new service order</b></h2>

<%= form_for(@so) do |f| %>
  <table id="table_new_so">
    <tr id="material_description">
      <div class="field">
        <td><%= f.label :material_description %></td>
        <td><%= f.text_field :material_description %></td>
      </div>
    </tr>
    <tr id="guide_number">
      <div class="field">
        <td><%= f.label :guide_number %></td>
        <td><%= f.text_field :guide_number %></td>
      </div>
    </tr>
    <tr id="sender_name">
      <div class="field">
        <td><%= f.label :sender_name %></td>
        <td><%= f.text_field :sender_name %></td>
      </div>
    </tr>
    <tr id="sender_phone">
      <div class="field">
        <td><%= f.label :sender_phone %></td>
        <td><%= f.text_field :sender_phone %></td>
      </div>
    </tr>
    <tr id="total_amount">
      <div class="field">
        <td><%= f.label :total_amount %></td>
        <td><%= f.text_field :total_amount %></td>
      </div>
    </tr>
    <tr id="material_class">
      <div class="field">
        <td><%= f.label :material_class_id %></td>
        <td><%= f.select :material_class_id, MaterialClass.all.collect{|p| [p.name, p.id]}, { include_blank: true } %></td>
      </div>
    </tr>
    <tr id="military_organization">
      <div class="field">
        <td><%= f.label :military_organization_id %></td>
        <td><%= f.select :military_organization_id, MilitaryOrganization.all.collect{|p| [p.name, p.id]}, { include_blank: true } %></td>
      </div>
    </tr>
  </table>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Back', sos_path %>

app/views/sos/show.html.erb
<h2><b>Showing Service Order</b></h2> 
<br>
<table id="so">
	<tr>
		<th>MATERIAL DESCRIPTION</th>
		<th>GUIDE NUMBER</th>
		<th>SENDER NAME</th>
		<th>SENDER PHONE</th>
		<th>TOTAL AMOUNT</th>
		<th>MATERIAL CLASS</th>
		<th>MILITARY ORGANIZATION</th>
	</tr>
	<tr>
		<td id="material_description"><%= @so.material_description %></td>
		<td id="guide_number"><%= @so.guide_number %></td>
		<td id="sender_name"><%= @so.sender_name %></td>
		<td id="sender_phone"><%= @so.sender_phone %></td>
		<td id="total_amount"><%= @so.total_amount %></td>
		<td id="material_class_name"><%= @so.material_class.name %></td>
		<td id="military_organization_acronym"><%= @so.military_organization.acronym %></td>
	</tr>

</table>
<br>

<h3><b>Showing Sub Service Orders</b></h3> 

<table id="sub_service_orders">
	<tr>
		<th>DESCRIPTION</th>
		<th>AMOUNT</th>
		<th>TECHNICAL</th>
		<th>SECTION MILITARY ORGANIZATION</th>
		<th colspan="4">OPTIONS</th>
	</tr>
	<% @so.sub_service_orders.each do |sub_service_order| %>
		<tr>
			<td id="sub_service_order_description_<%= sub_service_order.id %>"><%= sub_service_order.description %></td>
			<td id="sub_service_order_amount_<%= sub_service_order.id %>"><%= sub_service_order.amount %></td>
			<td id="sub_service_order_technical_<%= sub_service_order.id %>"><%= sub_service_order.technical %></td>
			<td id="sub_service_order_section_military_organization_acronym_<%= sub_service_order.id %>"><%= sub_service_order.section_military_organization.acronym %></td>
			<td id="sub_service_order_add_material_<%= sub_service_order.id %>"><%= link_to 'Add Material', new_so_sub_service_order_material_path(@so,sub_service_order) %></td>
			<td id="sub_service_order_show_<%= sub_service_order.id %>"><%= link_to 'Show', so_sub_service_order_path(@so, sub_service_order) %></td>
			<td id="sub_service_order_edit_<%= sub_service_order.id %>"><%= link_to 'Edit', edit_so_sub_service_order_path(@so, sub_service_order) %></td>
			<td id="sub_service_order_destroy_<%= sub_service_order.id %>"><%= link_to 'Destroy', so_sub_service_order_path(@so, sub_service_order), method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>

</table>
<br>
<%= link_to 'Create new sub service order', new_so_sub_service_order_path(@so) %>
<br>
<%= link_to 'Back', sos_path %>