config/routes.rb
Rails.application.routes.draw do  
  resources :sos do
    resources :sub_service_orders do
      resources :materials
    end
  end
  resources :material_classes
  resources :military_organizations
  resources :section_military_organizations
  
  

  root 'sos#index'

  get 'sub_service_orders/:id/purchase' => 'catalog#purchase', as: :purchase

end

app/models/section_military_organization.rb
class SectionMilitaryOrganization < ActiveRecord::Base
	validates_presence_of :name
  	validates_presence_of :acronym
  	validates_length_of :name, :minimum => 2
  	validates_length_of :name, :maximum => 30
  	validates_length_of :acronym, :minimum => 2
  	validates_length_of :acronym, :maximum => 20
  
  	#relacionamentos
  	has_many :sub_service_orders
end

app/controllers/section_military_organizations_controller.rb
class SectionMilitaryOrganizationsController < ApplicationController
	def index
		@section_military_organizations = SectionMilitaryOrganization.all
	end

	def new
		@section_military_organization = SectionMilitaryOrganization.new
	end
	
	def create
		@section_military_organization = SectionMilitaryOrganization.new(section_military_organization_params)
		if @section_military_organization.save then
			redirect_to section_military_organizations_path
		else
			render :new
		end
	end

	def destroy
		begin
			@section_military_organization = SectionMilitaryOrganization.find(params[:id])
			if @section_military_organization.sub_service_orders == nil or @section_military_organization.sub_service_orders.length == 0 then
				@section_military_organization.destroy
			end
				
			redirect_to section_military_organizations_path

		rescue ActiveRecord::RecordNotFound
			redirect_to section_military_organizations_path
		end		
	end

	def edit
		begin
			@section_military_organization = SectionMilitaryOrganization.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			redirect_to section_military_organizations_path
		end
	end

	def update
  		begin
  			@section_military_organization = SectionMilitaryOrganization.find(params[:id])
  			if @section_military_organization.update(section_military_organization_params) then 
  				redirect_to section_military_organizations_path
  			else
  				render :edit
  			end
  		rescue ActiveRecord::RecordNotFound
  			redirect_to section_military_organizations_path
  		end
	end
	# Never trust parameters from the scary internet, only allow the white list through.
    def section_military_organization_params
      params.require(:section_military_organization).permit(:name, :acronym)
    end
end

app/helpers/section_military_organizations_helper.rb
module SectionMilitaryOrganizationsHelper
end

app/views/section_military_organizations/edit.html.erb
<h2><b>Editing - section military organization</b></h2>

<%= form_for(@section_military_organization) do |f| %>
 <table id="section_military_organization">
    <tr id="name">
      <div class="field">
        <td id="name_label"><%= f.label :name %></td>
        <td id="name_textfield"><%= f.text_field :name %></td>
      </div>
    </tr>
    <tr id="acronym">
      <div class="field">
        <td id="acronym_label"><%= f.label :acronym %></td>
        <td id="acronym_textfield"><%= f.text_field :acronym %></td>
      </div>
    </tr>
  </table>
  <br>

  <div class="actions">
	  <%= f.submit %>
  </div>
 
<% end %>

<%= link_to 'Back', section_military_organizations_path %>

app/views/section_military_organizations/index.html.erb
<h2><b>SECTION MILITARY ORGANIZATIONS</b></h2> 
<br>
<table id="section_military_organizations">
	<tr id="header">
		<th>NAME</th>
		<th>ACRONYM</th>
		<th colspan="2">OPTIONS</th>
	</tr>
	<% @section_military_organizations.each do |section_military_organization| %>
		<tr>
			<td id="section_military_organization_name_<%= section_military_organization.id %>"><%= section_military_organization.name %></td>
			<td id="section_military_organization_acronym_<%= section_military_organization.id %>"><%= section_military_organization.acronym %></td>
			<td id="section_military_organization_edit_<%= section_military_organization.id %>"><%= link_to 'Edit', edit_section_military_organization_path(section_military_organization) %></td>
			<td id="section_military_organization_destroy_<%= section_military_organization.id %>"><%= link_to 'Destroy', section_military_organization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			
		</tr>
	<% end %>
</table>
<br>
<%= link_to 'Create new section military organization', new_section_military_organization_path %>
<br />
<%= link_to 'Back', sos_path %>

app/views/section_military_organizations/new.html.erb
<h2><b>Creating a new section military organization </b></h2>

<%= form_for(@section_military_organization) do |f| %>
  <table id="section_military_organization">
    <tr id="name">
      <div class="field">
        <td id="name_label"><%= f.label :name %></td>
        <td id="name_textfield"><%= f.text_field :name %></td>
      </div>
    </tr>
    <tr id="acronym">
      <div class="field">
        <td id="acronym_label"><%= f.label :acronym %></td>
        <td id="acronym_textfield"><%= f.text_field :acronym %></td>
      </div>
    </tr>
  </table>
  <br>
  
  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

<%= link_to 'Back', section_military_organizations_path %>