config/routes.rb
Rails.application.routes.draw do  
  resources :sos do
    resources :sub_service_orders do
      resources :materials
    end
  end
  resources :material_classes
  resources :military_organizations
  resources :section_military_organizations
  
  

  root 'sos#index'

  get 'sub_service_orders/:id/purchase' => 'catalog#purchase', as: :purchase

end

app/controllers/material_classes_controller.rb
class MaterialClassesController < ApplicationController
	def index
		@material_classes = MaterialClass.all
	end

	def new
		@material_class = MaterialClass.new
	end

	def create
		@material_class = MaterialClass.new(material_class_params)
		if @material_class.save then
			redirect_to material_classes_path
		else
			render :new
		end
	end

	def destroy
		begin
			@material_class = MaterialClass.find(params[:id])

			if @material_class.sos == nil or @material_class.sos.length == 0 then
				@material_class.destroy
			end

			redirect_to material_classes_path

		rescue ActiveRecord::RecordNotFound
			redirect_to material_classes_path
		end	
	end

	def edit
		begin
			@material_class = MaterialClass.find(params[:id])
		rescue ActiveRecord::RecordNotFound
			redirect_to material_classes_path
		end
	end

	def update
		begin
  			@material_class = MaterialClass.find(params[:id])
  			if @material_class.update(material_class_params) then 
  				redirect_to material_classes_path
  			else
  				render :edit
  			end
  		rescue ActiveRecord::RecordNotFound
  			redirect_to material_classes_path
  		end
	end

	# Never trust parameters from the scary internet, only allow the white list through.
    def material_class_params
      params.require(:material_class).permit(:name, :acronym)
    end
end

app/views/material_classes/edit.html.erb
<h2><b>Editing - material class</b></h2>

<%= form_for(@material_class) do |f| %>
<table id="table_edit_material_class">
  <tr id="name">
      <div class="field">
        <td id="name_label" ><%= f.label :name %></td>
        <td id="name_text_field"><%= f.text_field :name %></td>
      </div>
  </tr>
  <tr id="acronym">
      <div class="field">
        <td id="acronym_label"><%= f.label :acronym %></td>
        <td id="acronym_text_field"><%= f.text_field :acronym %></td>
      </div>
  </tr>
</table>
<br/>  
  <div class="actions">
	<%= f.submit %>
  </div>
 
<% end %>

<%= link_to 'Back', material_classes_path %>

app/views/material_classes/index.html.erb
<h2><b>MATERIAL CLASSES</b></h2> 
<br>
<table id="material_classes">
	<tr>
		<th>NAME</th>
		<th>ACRONYM</th>
		<th colspan="3">OPTIONS</th>
	</tr>
	<% @material_classes.each do |material_class| %>
		<tr>
			<td id="material_class_name_<%= material_class.id %>"><%= material_class.name %></td>
			<td id="material_class_acronym_<%= material_class.id %>"><%= material_class.acronym %></td>
			<td id="material_class_edit_<%= material_class.id %>"><%= link_to 'Edit', edit_material_class_path(material_class) %></td>
			<td id="material_class_destroy_<%= material_class.id %>"><%= link_to 'Destroy', material_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		</tr>
	<% end %>
</table>
<br>
<%= link_to 'Create new material class', new_material_class_path %>
<br />
<%= link_to 'Back', sos_path %>

app/views/material_classes/new.html.erb
<h2><b>Creating a new material class </b></h2>

<%= form_for(@material_class) do |f| %>
<table id="table_new_material_class">
  <tr id="name">
      <div class="field">
        <td id="name_label" ><%= f.label :name %></td>
        <td id="name_text_field"><%= f.text_field :name %></td>
      </div>
  </tr>
  <tr id="acronym">
      <div class="field">
        <td id="acronym_label"><%= f.label :acronym %></td>
        <td id="acronym_text_field"><%= f.text_field :acronym %></td>
      </div>
  </tr>
</table> 
  <br>  
  <div class="actions">
    <%= f.submit %>
  </div>


<% end %>

<%= link_to 'Back', material_classes_path %>